### ISSUE TITLE
[Bug]: `start-position` is not always scrolling to the first image

### ISSUE THREAD

**Issue by hasancruk** [hasancruk/cruk-carousel#3]

**Comment by hasanhaja** [comment]
Check for unique ids and data attributes. Slotted content is actually in light DOM so there could be a selection conflict.

**Comment by hasancruk** [comment]
I have an okay solution for this here in this commit: https://github.com/hasancruk/cruk-carousel/commit/e641b1d285bcdba854b63fef779821d7a2923457

It wasn't due to a incorrect selection or anything like that. I think the browser does things to preserve scroll position on reload and that behavior is interferring with scroll position setting. This approach introduces a delay and synchronizes it to an animation frame, which resolves the issue most of the time. The incorrect start image is selected some of the time, but I've mostly addressed the issue now.
